### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Waisse** [AllTheMods/ATM-Expert#60] opened 2017-08-26 23:42 UTC
Can't craft Embers crystal with alchemy catalyst

http://i.imgur.com/BtM15jD.png

And this one doesn't return a bucket : 

http://i.imgur.com/HaNNmbq.png

**Comment by MigukNamja** [comment] 2017-08-28 17:45
First one fixed in 1.1.0 and duplicate of Issue #49 

2nd one working as designed/intended. It's an alternate recipe. The most efficient way to get Embers crystals and shards is still Embers itself. This is for people that can't stand Embers and want it over and done with already.

**Closed as completed by MigukNamja** 2017-08-28 17:45 UTC
Labels: bug, duplicate
